# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e639ac3dd3aaa77f4dc4db5045564183f8f3e697dc0291500ea75185879825b2088d4ba7a4472487acf6b4b655e022c4e6eb46e86ad442e986b476e65a4b369d

test:
  secret_key_base: eb43b3c9bad96e1a4ceff984796fcc4c88ad509ba198ac0ea94293d116e0076db1d799e055f83b9a0f4469ce79f6c9fb1d0a5fc8d7684da68c118771b2c3e457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
